# Generated by Django 6.0.1 on 2026-05-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
